<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xsd:element name="dockerCompose">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="version" type="xsd:string"/>
        <xsd:element name="services" minOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="service" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="image" type="xsd:string"/>
                    <xsd:element name="environment" minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="var" minOccurs="0" maxOccurs="unbounded">
                            <xsd:complexType>
                              <xsd:simpleContent>
                                <xsd:extension base="xsd:string">
                                  <xsd:attribute name="name" type="xsd:string" use="required"/>
                                </xsd:extension>
                              </xsd:simpleContent>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="ports" minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="port" type="xsd:string" maxOccurs="unbounded"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="healthcheck" minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="test" type="xsd:string"/>
                          <xsd:element name="interval" type="xsd:string"/>
                          <xsd:element name="timeout" type="xsd:string"/>
                          <xsd:element name="retries" type="xsd:positiveInteger"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="name" type="xsd:string" use="required"/>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>
